name: astrodatapy

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx>=1.4
    - pandoc
    - nbconvert
    - ipykernel
    - pip:
       - nbsphinx
#       - dependency_from_pip
