language: python 
sudo: required

env:
  global:
    - NUMPY_VERISON=1.13
notifications:
  email:
    recipients:
      - yuxiang.l.qin@gmail.com
    on_success: change
    on_failure: always

matrix:
  fast_finish: true

  include:        
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=2.7
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=3.5
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=3.6
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create -q --yes -n test python=$PYTHON_VERSION 
  - source activate test
  - python setup.py build
  - python setup.py install
 
before_script:

script:
    - cd astrodatapy/tests/
    - python test_astrodatapy.py
